[build]
  command = "pip install -r requirements.txt"
  publish = "app"

[build.environment]
  PYTHON_VERSION = "3.8.10"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200

[functions]
  directory = "functions"